package domain;

public enum SpecificPosition {
    GOALKEEPER, DEFENDER, LEFT_BACK, RIGHT_BACK,
    DEFENSIVE_MIDFIELDER, MIDFIELDER, ATTACKING_MIDFIELDER,
    RIGHT_WINGER, LEFT_WINGER, CENTER_WINGER
}
